Deployment Testing - 11

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -24,17 +24,26 @@ steps:
       #- "plan"
       - "-c"
       - |
-        terraform plan || true
+       terraform plan -detailed-exitcode || TF_EXITCODE=$?
+        if [[ $TF_EXITCODE -eq 0 || $TF_EXITCODE -eq 2 ]]; then
+          echo "Terraform plan successful or with changes"
+        elif [[ $TF_EXITCODE -eq 1 ]]; then
+          echo "Terraform plan failed"
+            # Handle failure if needed
+          exit 1
+        elif [[ $TF_EXITCODE -eq 3 ]]; then
+          echo "No changes to apply, Terraform succeeded"
+        else
+          echo "Terraform exited with an unexpected code: $TF_EXITCODE"
+          exit 1
+        fi
 
   - name: "hashicorp/terraform:latest"
     dir: "terraform"
-    entrypoint: "/bin/sh"
     args:
-#      - "apply"
-#      - "-auto-approve"
-      - "-c"
-      - |
-        terraform apply -auto-approve || true
+      - "apply"
+      - "-auto-approve"
+
 
 
     # build the container name
